stages:
  - pages

pages:
  image: registry.gitlab.com/formations-kgaut/template-reveal-js:latest
  stage: pages
  script:
    - mv /public public
    - mv slides.md public/slides.md
    - mv static public/static
    - mv css/reset.css public/dist/reset.css
    - mv css/monokai.css public/plugin/highlight/monokai.css
    - echo $CI_PROJECT_TITLE
    - sed -i "s/\[TITLE\]/$CI_PROJECT_TITLE/g" public/index.html
  artifacts:
    paths:
      - public


